### PR TITLE
Sidebar Fixes and Cleanup

### LINKED ISSUE #3: Sidebar Tabs User Control
Currently the user does not have a lot of control of the tab they have saved and this makes it difficult for multitasking. By making it so that the tab item created leads to an extension page with more controls and parses the url we can achieve the goal for further control over the page. This can be fully done with the Pulse Sidebar API and is a good enhancement.

### PR DESCRIPTION
**Pull request by PressJump**
Changes styling of sidebar-tabs, forming it with Firefox design practices and utilities the color scheme of the browser theme from issue #1 . This also fixes the race condition found on #2

### CODE REVIEW

**Comment by PressJump** [comment]
Rewrite of extension functions to eliminate race condition and attach sidebar given IDs for removing specific items on the sidebar rather than using url's.

**Comment by PressJump** [comment]
Fixes issues related to the race condition and implements dark mode to sidebar-tabs. Further changes relating to styling can be done on another branch as this fixes structural issues that is blocking an update.

File: js/background.js [hunk 1]
```diff
@@ -10,36 +10,36 @@ getFromStorage().then(createSidebarItems);
...
+        if (storagearray.sidebaritems[i].id == itemId) {
+            storagearray.sidebaritems.splice(i, 1);
         }
     }
 
-    browser.storage.local.set(storagearray);
+    await browser.storage.local.set(storagearray);
 }
 
 browser.sidebars.onRemove.addListener((itemId) => {
```
Comment (trickypr) [inline js/background.js]: On remove will run multiple remove tasks in parallel. Whilst awaiting the storage calls might reduce some issues at creation, there is still a chance that the storage calls will resolve out of order (primarily on slower systems). You **must** lock / use a mutex to control access to the storage otherwise a race condition still exists.

File: js/background.js [hunk 2]
```diff
@@ -10,36 +10,36 @@ getFromStorage().then(createSidebarItems);
...
-        if (storageitems[i].webviewUrl == item.webviewUrl) {
-            storageitems.splice(i, 1);
+    for (let i = 0; i < storagearray.sidebaritems.length; i++) {
+        if (storagearray.sidebaritems[i].id == itemId) {
+            storagearray.sidebaritems.splice(i, 1);
         }
     }
 
-    browser.storage.local.set(storagearray);
+    await browser.storage.local.set(storagearray);
```
Comment (trickypr) [inline js/background.js]: This call needs to be protected by a mutex.

File: js/background.js [hunk 3]
```diff
@@ -10,36 +10,36 @@ getFromStorage().then(createSidebarItems);
...
-        browser.sidebars.add({
+        var item = await browser.sidebars.add({
             title: sidebaritems.sidebaritems[i].title,
             iconUrl: sidebaritems.sidebaritems[i].iconUrl,
             webviewUrl: sidebaritems.sidebaritems[i].webviewUrl,
         });
+        sidebaritems.sidebaritems[i].id = item;
     }
+
+    await browser.storage.local.set(sidebaritems);
```
Comment (trickypr) [inline js/background.js]: This call needs to be protected by a mutex.

File: js/main.js [hunk 4]
```diff
@@ -1,77 +1,108 @@
...
-          //remove listener
-          browser.tabs.onUpdated.removeListener(listener);
-          browser.tabs.get(tab.id).then(function(tab) {
-            //create new sidebar item
-            browser.sidebars.add({
-              title: tab.title,
-              iconUrl: pageIcon,
-              webviewUrl: tab.url,
-            });
+  await browser.storage.local.set(storagearray);
```
Comment (trickypr) [inline js/main.js]: This call needs to be protected by a mutex.

File: js/main.js [hunk 5]
```diff
@@ -1,77 +1,108 @@
...
-    browser.sidebars.add({
-      title: pageURL,
-      iconUrl: pageIcon,
-      webviewUrl: pageURL,
-    });
-  }
+    }
+    else
+    {
+      createSidebarItem(pageURL, pageIcon, "https://"+page);
```
Comment (trickypr) [inline js/main.js]: This is an async function

**Review by trickypr — CHANGES_REQUESTED** [review]
I think you misunderstand the race condition. It is caused by out of order storage calls / resolutions. You should only ever be making one call to storage at a time. Take this example:

```ts
const a: Promise<any> = addPage(...);
const b: Promise<any> = removeSidebarItems(...);
const c: Promise<any> = createSidebarItem(...);
```

Spidermonkey batches event calls and runs them at the same time. It **does not** await them, so they run in parallel. This means that `a` may read the storage and cache it in `storagearray` and wait for `browser.sidebars.add` to resolve. 

However, as it resolves, spidermonkey is executing `b` and `c`, which both modify storage and will run much faster because they are simpler. They will call `browser.storage.local.set` before `a`'s `browser.storage.local.set`. Because `a` calls `browser.storage.local.set` later and `storagearray` is never synced, it will overwrite the changes created by `b` and `c`.

The only way to avoid this is to force the storage calls to be performed synchronously, via a mutex / lock. JS doesn't include a mutex in the standard library, so you will have to implement it yourself, with something like this:

```ts
class Mutex {
    private locked = false

    private sleep(): Promise<void> {
        return new Promise((res) => setTimeout(res, 1))
    }

    async lock(): Promise<{unlock: () => void}> {
        while (this.locked) {
            await this.sleep()
        }
        
        this.locked = true

        return {unlock: () => (this.locked = false)}
    }
}

// This **must** be stored extension wide
let mutex = new Mutex();

async function createSidebarItem(...args) {
    let {unlock} = await mutex.lock();

    // Storage code here

    unlock()
}
```

So long as you wrap this around all of the storage calls in a function, this will prevent a race condition from occurring.

**Review by trickypr — COMMENTED** [review]
I have made changes to fix the issues I raised, can you review @PressJump?

**Review by PressJump — COMMENTED** [review]
LGTM

**Review by trickypr — APPROVED** [review]
